print('prueba de subida desde MAC')
print('prueba de subida desde MAC2')
print('prueba de subida desde MAC3')
print('prueba de subida desde MAC4')
print('prueba de subida desde MAC5')
print('prueba de subida desde Strix &')